# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
dependencies:
- cython
- openssl
- pip
- python=2.7.11
- readline
- setuptools
- sqlite
- tk
- wheel
- zlib
- numpy
- scipy
- pandas
- matplotlib
- nose
- ipython
